### ISSUE TITLE
Broken image with phpqa 1.9

### ISSUE THREAD

**Issue by marcosh** [eko3alpha/docker-phpqa#2]
The image actually present on docker hub is using phpqa with version 1.9 and it seems to be broken because it does not hava Twing among the composer dependencies.

It would be nice to update the image on docker hub with version 1.10

**Comment by eko3alpha** [comment]
I see what you mean, I'm now getting this error with the latest version of phpqa with the --update-no-dev "symfony/console:~2.8" flag.
```
  [Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Twig_Loader_Filesystem' not found    
```

I'll update the dockerfile.

Thanks!
